# This is a basic workflow to help me: Verify Commit and Merge

on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  verify_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Track large files
        run: |
          large_files=$(find . -type f -size +50M | grep -v ".git/lfs")
          if [ -n "$large_files" ]; then
            echo "$large_files" | xargs -I {} git lfs track {}
            git add .gitattributes
            if ! git diff --cached --quiet; then
              git commit -m "Track large files using Git LFS"
            else
              echo "No changes to commit"
            fi
          fi
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true  # Ensure Git LFS files are pulled

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify Git LFS Tracking
        run: |
          git lfs ls-files || echo "No LFS-tracked files found"
      - name: Reject Untracked Large Files
        run: |
          large_files=$(find . -type f -size +50M | grep -v ".git/lfs")
          if [ -n "$large_files" ]; then
            echo "Error: The following files exceed 50MB and are not tracked by Git LFS:"
            echo "$large_files"
            exit 1
          fi
      - name: Auto-Merge If Safe
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$branch" != "main" ]; then
            git checkout main
            git merge --ff-only "$branch" || echo "Merge conflict detected, manual merge required"
            git push origin main || echo "Push failed, check logs"
          fi

